#!/usr/bin/env python3
"""Synthesise the game's sound effects.

Every sound in vectorwake is ours, per docs/design/identity.md, and the
cheapest way to guarantee that is to generate them from arithmetic rather than
record or source them. This script is the master: the .wav files next to it in
client/sounds/ are its output, checked in so a build needs nothing but bob,
and regenerated by re-running it.

    python3 client/tools/mksounds.py client/sounds

The vocabulary is deliberately narrow and matches the art direction. Weapons
are short and bright with a hard transient. Explosions are noise under a
descending sine, which is what gives a blast a body rather than a hiss. The
interface ticks. Nothing rings for longer than the thing that caused it is on
screen.

Standard library only: `wave` and `math`. No numpy, so this runs anywhere the
repository does.
"""

import math
import os
import random
import struct
import sys
import wave

RATE = 22050


def env(t, dur, attack=0.004, curve=3.0):
    """Fast attack, exponential decay, silent at exactly `dur`."""
    if t < attack:
        return t / attack
    x = (t - attack) / max(1e-6, dur - attack)
    if x >= 1.0:
        return 0.0
    return (1.0 - x) ** curve


class Voice:
    """A mono buffer with the handful of shaping tools these sounds need."""

    def __init__(self, dur):
        self.n = int(dur * RATE)
        self.dur = dur
        self.buf = [0.0] * self.n

    def sine(self, f0, f1, gain, curve=1.0, phase=0.0):
        """A swept sine. Phase is integrated so the sweep has no clicks."""
        ph = phase
        for i in range(self.n):
            t = i / RATE
            x = (t / self.dur) ** curve
            f = f0 + (f1 - f0) * x
            ph += 2 * math.pi * f / RATE
            self.buf[i] += math.sin(ph) * gain * env(t, self.dur)
        return self

    def saw(self, f0, f1, gain, curve=1.0):
        ph = 0.0
        for i in range(self.n):
            t = i / RATE
            f = f0 + (f1 - f0) * (t / self.dur) ** curve
            ph = (ph + f / RATE) % 1.0
            self.buf[i] += (2 * ph - 1) * gain * env(t, self.dur)
        return self

    def square(self, f0, f1, gain, duty=0.5, curve=1.0):
        ph = 0.0
        for i in range(self.n):
            t = i / RATE
            f = f0 + (f1 - f0) * (t / self.dur) ** curve
            ph = (ph + f / RATE) % 1.0
            self.buf[i] += (1.0 if ph < duty else -1.0) * gain * env(t, self.dur)
        return self

    def noise(self, gain, cutoff=6000.0, cutoff_end=None, curve=2.0, rng=None):
        """White noise through a one-pole lowpass whose corner can sweep.

        A sweep from bright to dark is what makes a burst read as an
        explosion rather than as static: the high end leaves first, exactly
        as air absorbs it.
        """
        rng = rng or random.Random(1)
        cutoff_end = cutoff if cutoff_end is None else cutoff_end
        y = 0.0
        for i in range(self.n):
            t = i / RATE
            x = t / self.dur
            fc = cutoff + (cutoff_end - cutoff) * x
            a = 1.0 - math.exp(-2 * math.pi * max(20.0, fc) / RATE)
            y += a * (rng.uniform(-1.0, 1.0) - y)
            self.buf[i] += y * gain * env(t, self.dur, curve=curve)
        return self

    # --- looping ----------------------------------------------------------
    #
    # A held sound is played end to end forever, so the last sample has to lead
    # into the first one. Two rules do it: no envelope, and everything periodic
    # in the buffer's own length.

    def loop_sine(self, f, gain, phase=0.0):
        """A sine snapped to a whole number of cycles in the buffer.

        Off by a fraction of a cycle and the wrap is a step, which is a click
        at exactly the loop rate -- the most recognisable defect a looping
        sound has.
        """
        cycles = max(1, round(f * self.dur))
        for i in range(self.n):
            self.buf[i] += math.sin(phase + 2 * math.pi * cycles * i / self.n) * gain
        return self

    def loop_noise(self, gain, cutoff, rng=None):
        """Lowpassed noise that wraps.

        The filter is run twice around the same buffer and only the second lap
        is kept, so its state entering the loop is the state it left with. The
        noise itself is circular by construction, so nothing has to be
        crossfaded.
        """
        rng = rng or random.Random(1)
        raw = [rng.uniform(-1.0, 1.0) for _ in range(self.n)]
        a = 1.0 - math.exp(-2 * math.pi * max(20.0, cutoff) / RATE)
        y = 0.0
        for i in range(self.n):        # a lap to settle the filter's state
            y += a * (raw[i] - y)
        for i in range(self.n):        # and a lap that is kept
            y += a * (raw[i] - y)
            self.buf[i] += y * gain
        return self

    def highpass(self, fc):
        a = math.exp(-2 * math.pi * fc / RATE)
        prev_x, prev_y = 0.0, 0.0
        for i in range(self.n):
            x = self.buf[i]
            prev_y = a * (prev_y + x - prev_x)
            prev_x = x
            self.buf[i] = prev_y
        return self

    def drive(self, k):
        """Soft clipping. Gives a blast weight without letting it clip hard."""
        for i in range(self.n):
            self.buf[i] = math.tanh(self.buf[i] * k) / math.tanh(k)
        return self

    def fade_out(self, seconds=0.008):
        m = min(self.n, int(seconds * RATE))
        for i in range(m):
            self.buf[self.n - 1 - i] *= i / m
        return self

    def normalise(self, peak=0.86):
        hi = max(1e-6, max(abs(v) for v in self.buf))
        k = peak / hi
        self.buf = [v * k for v in self.buf]
        return self

    def write(self, path, loop=False):
        # A loop must not fade: the fade is a hole in the middle of the sound
        # once the buffer is played end to end.
        if not loop:
            self.fade_out()
        self.normalise()
        frames = bytearray()
        for v in self.buf:
            s = int(max(-1.0, min(1.0, v)) * 32767)
            frames += struct.pack("<h", s)
        with wave.open(path, "wb") as w:
            w.setnchannels(1)
            w.setsampwidth(2)
            w.setframerate(RATE)
            w.writeframes(bytes(frames))
        print("%-12s %5.0f ms  %6d bytes" % (
            os.path.basename(path), self.dur * 1000, len(frames)))


# --- the kit ---------------------------------------------------------------

def gun():
    """A bolt leaving the rail: bright, over before it registers."""
    v = Voice(0.085)
    v.square(1750, 460, 0.55, duty=0.32, curve=0.45)
    v.sine(2400, 700, 0.30, curve=0.4)
    v.noise(0.16, 7000, 900, rng=random.Random(11))
    return v.drive(1.6)


def bomb():
    """Heavier and slower than a gun, so the ear knows which one fired."""
    v = Voice(0.24)
    v.saw(280, 78, 0.5, curve=0.6)
    v.sine(160, 46, 0.42, curve=0.7)
    v.noise(0.22, 2600, 260, rng=random.Random(23))
    return v.drive(1.9)


def blast():
    """A bomb going off: noise for the air, a falling sine for the body."""
    v = Voice(0.55)
    v.noise(0.62, 5200, 190, curve=2.4, rng=random.Random(37))
    v.sine(190, 38, 0.55, curve=0.5)
    v.sine(96, 30, 0.35, curve=0.6)
    return v.drive(2.1)


def death():
    """A ship coming apart. The one event allowed a full second."""
    v = Voice(0.95)
    v.noise(0.66, 4200, 120, curve=2.0, rng=random.Random(53))
    v.sine(240, 32, 0.5, curve=0.45)
    v.sine(120, 24, 0.42, curve=0.55)
    v.saw(90, 26, 0.22, curve=0.7)
    return v.drive(2.4)


def hit():
    """Something struck your hull. A crack, not a tone."""
    v = Voice(0.07)
    v.noise(0.7, 9000, 1400, curve=3.0, rng=random.Random(67))
    v.sine(620, 210, 0.3, curve=0.5)
    return v.highpass(300).drive(1.5)


def bounce():
    """A wall. Dull, brief, and quiet enough to hear forty times a minute."""
    v = Voice(0.075)
    v.sine(340, 150, 0.5, curve=0.6)
    v.noise(0.2, 2200, 500, rng=random.Random(71))
    return v.drive(1.3)


def spawn():
    """Coming back: rising, clean, and unmistakably not a weapon."""
    v = Voice(0.32)
    v.sine(220, 880, 0.42, curve=1.5)
    v.sine(330, 1320, 0.22, curve=1.5)
    v.noise(0.1, 900, 5200, curve=1.2, rng=random.Random(83))
    return v


def prize():
    """A green picked up. Two intervals up, because that is what reward
    sounds like and arguing with it is not worth the novelty."""
    v = Voice(0.22)
    v.sine(880, 880, 0.34)
    a = Voice(0.22)
    a.sine(1320, 1320, 0.3)
    for i in range(min(v.n, a.n)):
        d = int(0.055 * RATE)
        if i >= d:
            v.buf[i] += a.buf[i - d]
    return v


def charge():
    """A charge spent: a short downward chirp with a body to it, so it reads
    as something leaving your hands rather than a shot going out."""
    v = Voice(0.18)
    v.sine(700, 300, 0.34, curve=1.3)
    v.noise(0.07, 400, 2600, curve=1.5, rng=random.Random(41))
    return v


def rust():
    """A green that took something. The prize sound's intervals, downward and
    duller: the same event going the other way, which is what it is."""
    v = Voice(0.26)
    v.sine(660, 494, 0.3, curve=0.8)
    a = Voice(0.26)
    a.sine(440, 330, 0.26, curve=0.8)
    for i in range(min(v.n, a.n)):
        d = int(0.06 * RATE)
        if i >= d:
            v.buf[i] += a.buf[i - d]
    v.noise(0.05, 200, 1400, curve=1.4, rng=random.Random(17))
    return v


def flag():
    """A flag changing hands: two tones, the second higher, quick."""
    v = Voice(0.3)
    v.sine(440, 460, 0.3)
    b = Voice(0.3)
    b.sine(660, 700, 0.3)
    d = int(0.08 * RATE)
    for i in range(d, v.n):
        v.buf[i] += b.buf[i - d]
    return v


def thrust():
    """A held drive. Loops for as long as the pilot holds the key.

    Rocket, not engine: mostly filtered noise, with two low partials for a
    body so it does not read as tape hiss. Half a second is long enough that
    the ear cannot hear the repeat and short enough to be a small file.
    """
    v = Voice(0.5)
    v.loop_noise(0.60, 520, rng=random.Random(101))    # the rumble
    v.loop_noise(0.16, 2600, rng=random.Random(103))   # a little air over it
    v.loop_sine(58, 0.26)
    v.loop_sine(87, 0.13)
    v.loop_sine(146, 0.06)
    return v.drive(1.25)


def ui_move():
    v = Voice(0.035)
    v.square(1200, 900, 0.4, duty=0.4)
    v.noise(0.14, 6000, 2000, rng=random.Random(97))
    return v.highpass(400)


def ui_go():
    v = Voice(0.16)
    v.sine(520, 1040, 0.42, curve=1.4)
    v.square(260, 520, 0.16, duty=0.3, curve=1.4)
    return v.drive(1.4)


KIT = {
    "gun": gun, "bomb": bomb, "blast": blast, "death": death, "hit": hit,
    "bounce": bounce, "spawn": spawn, "prize": prize, "rust": rust,
    "charge": charge, "flag": flag,
    "thrust": thrust, "ui_move": ui_move, "ui_go": ui_go,
}

SOUND_COMPONENT = """sound: "/sounds/%s.wav"
looping: %d
group: "master"
gain: %.2f
pan: 0.0
speed: 1.0
loopcount: 0
"""

# Per-sound trim, so the mix is balanced at the source and the game never has
# to remember that bombs are loud. Thrust is held down for minutes at a time
# and everything else has to be audible over it, so it sits well under them.
GAIN = {
    "gun": 0.30, "bomb": 0.55, "blast": 0.80, "death": 0.85, "hit": 0.40,
    "bounce": 0.30, "spawn": 0.45, "prize": 0.45, "rust": 0.50,
    "charge": 0.55, "flag": 0.55,
    "thrust": 0.13, "ui_move": 0.35, "ui_go": 0.55,
}

# The ones that play until they are stopped. `loopcount: 0` with looping on is
# Defold's "forever".
LOOPING = {"thrust"}


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "client/sounds"
    os.makedirs(out, exist_ok=True)
    for name, make in sorted(KIT.items()):
        loop = name in LOOPING
        make().write(os.path.join(out, name + ".wav"), loop=loop)
        with open(os.path.join(out, name + ".sound"), "w") as f:
            f.write(SOUND_COMPONENT % (name, 1 if loop else 0, GAIN[name]))


if __name__ == "__main__":
    main()
