#!/usr/bin/env python3
"""Synthesise the game's sound effects.

Every sound in vectorwake is ours, per docs/design/identity.md, and the
cheapest way to guarantee that is to generate them from arithmetic rather than
record or source them. This script is the master: the .wav files next to it in
client/sounds/ are its output, checked in so a build needs nothing but bob,
and regenerated by re-running it.

    python3 client/tools/mksounds.py client/sounds

The vocabulary is deliberately narrow and matches the art direction. Weapons
are short and bright with a hard transient. Explosions are noise under a
descending sine, which is what gives a blast a body rather than a hiss. The
interface ticks. Nothing rings for longer than the thing that caused it is on
screen.

Standard library only: `wave` and `math`. No numpy, so this runs anywhere the
repository does.
"""

import math
import os
import random
import struct
import sys
import wave

RATE = 22050


def env(t, dur, attack=0.004, curve=3.0):
    """Fast attack, exponential decay, silent at exactly `dur`."""
    if t < attack:
        return t / attack
    x = (t - attack) / max(1e-6, dur - attack)
    if x >= 1.0:
        return 0.0
    return (1.0 - x) ** curve


class Voice:
    """A mono buffer with the handful of shaping tools these sounds need."""

    def __init__(self, dur, rate=RATE):
        self.rate = rate
        self.n = int(dur * rate)
        self.dur = dur
        self.buf = [0.0] * self.n

    def sine(self, f0, f1, gain, curve=1.0, phase=0.0):
        """A swept sine. Phase is integrated so the sweep has no clicks."""
        ph = phase
        for i in range(self.n):
            t = i / self.rate
            x = (t / self.dur) ** curve
            f = f0 + (f1 - f0) * x
            ph += 2 * math.pi * f / self.rate
            self.buf[i] += math.sin(ph) * gain * env(t, self.dur)
        return self

    def saw(self, f0, f1, gain, curve=1.0):
        ph = 0.0
        for i in range(self.n):
            t = i / self.rate
            f = f0 + (f1 - f0) * (t / self.dur) ** curve
            ph = (ph + f / self.rate) % 1.0
            self.buf[i] += (2 * ph - 1) * gain * env(t, self.dur)
        return self

    def square(self, f0, f1, gain, duty=0.5, curve=1.0):
        ph = 0.0
        for i in range(self.n):
            t = i / self.rate
            f = f0 + (f1 - f0) * (t / self.dur) ** curve
            ph = (ph + f / self.rate) % 1.0
            self.buf[i] += (1.0 if ph < duty else -1.0) * gain * env(t, self.dur)
        return self

    def noise(self, gain, cutoff=6000.0, cutoff_end=None, curve=2.0, rng=None):
        """White noise through a one-pole lowpass whose corner can sweep.

        A sweep from bright to dark is what makes a burst read as an
        explosion rather than as static: the high end leaves first, exactly
        as air absorbs it.
        """
        rng = rng or random.Random(1)
        cutoff_end = cutoff if cutoff_end is None else cutoff_end
        y = 0.0
        for i in range(self.n):
            t = i / self.rate
            x = t / self.dur
            fc = cutoff + (cutoff_end - cutoff) * x
            a = 1.0 - math.exp(-2 * math.pi * max(20.0, fc) / self.rate)
            y += a * (rng.uniform(-1.0, 1.0) - y)
            self.buf[i] += y * gain * env(t, self.dur, curve=curve)
        return self

    # --- looping ----------------------------------------------------------
    #
    # A held sound is played end to end forever, so the last sample has to lead
    # into the first one. Two rules do it: no envelope, and everything periodic
    # in the buffer's own length.

    def loop_sine(self, f, gain, phase=0.0):
        """A sine snapped to a whole number of cycles in the buffer.

        Off by a fraction of a cycle and the wrap is a step, which is a click
        at exactly the loop rate -- the most recognisable defect a looping
        sound has.
        """
        cycles = max(1, round(f * self.dur))
        for i in range(self.n):
            self.buf[i] += math.sin(phase + 2 * math.pi * cycles * i / self.n) * gain
        return self

    def loop_noise(self, gain, cutoff, rng=None):
        """Lowpassed noise that wraps.

        The filter is run twice around the same buffer and only the second lap
        is kept, so its state entering the loop is the state it left with. The
        noise itself is circular by construction, so nothing has to be
        crossfaded.
        """
        rng = rng or random.Random(1)
        raw = [rng.uniform(-1.0, 1.0) for _ in range(self.n)]
        a = 1.0 - math.exp(-2 * math.pi * max(20.0, cutoff) / self.rate)
        y = 0.0
        for i in range(self.n):        # a lap to settle the filter's state
            y += a * (raw[i] - y)
        for i in range(self.n):        # and a lap that is kept
            y += a * (raw[i] - y)
            self.buf[i] += y * gain
        return self

    def highpass(self, fc):
        a = math.exp(-2 * math.pi * fc / self.rate)
        prev_x, prev_y = 0.0, 0.0
        for i in range(self.n):
            x = self.buf[i]
            prev_y = a * (prev_y + x - prev_x)
            prev_x = x
            self.buf[i] = prev_y
        return self

    def drive(self, k):
        """Soft clipping. Gives a blast weight without letting it clip hard."""
        for i in range(self.n):
            self.buf[i] = math.tanh(self.buf[i] * k) / math.tanh(k)
        return self

    def fade_out(self, seconds=0.008):
        m = min(self.n, int(seconds * self.rate))
        for i in range(m):
            self.buf[self.n - 1 - i] *= i / m
        return self

    def normalise(self, peak=0.86):
        hi = max(1e-6, max(abs(v) for v in self.buf))
        k = peak / hi
        self.buf = [v * k for v in self.buf]
        return self

    def write(self, path, loop=False):
        # A loop must not fade: the fade is a hole in the middle of the sound
        # once the buffer is played end to end.
        if not loop:
            self.fade_out()
        self.normalise()
        frames = bytearray()
        for v in self.buf:
            s = int(max(-1.0, min(1.0, v)) * 32767)
            frames += struct.pack("<h", s)
        with wave.open(path, "wb") as w:
            w.setnchannels(1)
            w.setsampwidth(2)
            w.setframerate(self.rate)
            w.writeframes(bytes(frames))
        print("%-12s %5.0f ms  %6d bytes" % (
            os.path.basename(path), self.dur * 1000, len(frames)))


# --- the kit ---------------------------------------------------------------

def gun():
    """A bolt leaving the rail: bright, over before it registers."""
    v = Voice(0.085)
    v.square(1750, 460, 0.55, duty=0.32, curve=0.45)
    v.sine(2400, 700, 0.30, curve=0.4)
    v.noise(0.16, 7000, 900, rng=random.Random(11))
    return v.drive(1.6)


def bomb():
    """Heavier and slower than a gun, so the ear knows which one fired."""
    v = Voice(0.24)
    v.saw(280, 78, 0.5, curve=0.6)
    v.sine(160, 46, 0.42, curve=0.7)
    v.noise(0.22, 2600, 260, rng=random.Random(23))
    return v.drive(1.9)


def blast():
    """A bomb going off: noise for the air, a falling sine for the body."""
    v = Voice(0.55)
    v.noise(0.62, 5200, 190, curve=2.4, rng=random.Random(37))
    v.sine(190, 38, 0.55, curve=0.5)
    v.sine(96, 30, 0.35, curve=0.6)
    return v.drive(2.1)


def death():
    """A ship coming apart. The one event allowed a full second."""
    v = Voice(0.95)
    v.noise(0.66, 4200, 120, curve=2.0, rng=random.Random(53))
    v.sine(240, 32, 0.5, curve=0.45)
    v.sine(120, 24, 0.42, curve=0.55)
    v.saw(90, 26, 0.22, curve=0.7)
    return v.drive(2.4)


def hit():
    """Something struck your hull. A crack, not a tone."""
    v = Voice(0.07)
    v.noise(0.7, 9000, 1400, curve=3.0, rng=random.Random(67))
    v.sine(620, 210, 0.3, curve=0.5)
    return v.highpass(300).drive(1.5)


def bounce():
    """A wall. Dull, brief, and quiet enough to hear forty times a minute."""
    v = Voice(0.075)
    v.sine(340, 150, 0.5, curve=0.6)
    v.noise(0.2, 2200, 500, rng=random.Random(71))
    return v.drive(1.3)


def spawn():
    """Coming back: rising, clean, and unmistakably not a weapon."""
    v = Voice(0.32)
    v.sine(220, 880, 0.42, curve=1.5)
    v.sine(330, 1320, 0.22, curve=1.5)
    v.noise(0.1, 900, 5200, curve=1.2, rng=random.Random(83))
    return v


def prize():
    """A green picked up. Two intervals up, because that is what reward
    sounds like and arguing with it is not worth the novelty."""
    v = Voice(0.22)
    v.sine(880, 880, 0.34)
    a = Voice(0.22)
    a.sine(1320, 1320, 0.3)
    for i in range(min(v.n, a.n)):
        d = int(0.055 * RATE)
        if i >= d:
            v.buf[i] += a.buf[i - d]
    return v


def charge():
    """A charge spent: a short downward chirp with a body to it, so it reads
    as something leaving your hands rather than a shot going out."""
    v = Voice(0.18)
    v.sine(700, 300, 0.34, curve=1.3)
    v.noise(0.07, 400, 2600, curve=1.5, rng=random.Random(41))
    return v


def rust():
    """A green that took something. The prize sound's intervals, downward and
    duller: the same event going the other way, which is what it is."""
    v = Voice(0.26)
    v.sine(660, 494, 0.3, curve=0.8)
    a = Voice(0.26)
    a.sine(440, 330, 0.26, curve=0.8)
    for i in range(min(v.n, a.n)):
        d = int(0.06 * RATE)
        if i >= d:
            v.buf[i] += a.buf[i - d]
    v.noise(0.05, 200, 1400, curve=1.4, rng=random.Random(17))
    return v


def flag():
    """A flag changing hands: two tones, the second higher, quick."""
    v = Voice(0.3)
    v.sine(440, 460, 0.3)
    b = Voice(0.3)
    b.sine(660, 700, 0.3)
    d = int(0.08 * RATE)
    for i in range(d, v.n):
        v.buf[i] += b.buf[i - d]
    return v


def thrust():
    """A held drive. Loops for as long as the pilot holds the key.

    Rocket, not engine: mostly filtered noise, with two low partials for a
    body so it does not read as tape hiss. Half a second is long enough that
    the ear cannot hear the repeat and short enough to be a small file.
    """
    v = Voice(0.5)
    v.loop_noise(0.60, 520, rng=random.Random(101))    # the rumble
    v.loop_noise(0.16, 2600, rng=random.Random(103))   # a little air over it
    v.loop_sine(58, 0.26)
    v.loop_sine(87, 0.13)
    v.loop_sine(146, 0.06)
    return v.drive(1.25)


# --- the soundtrack --------------------------------------------------------
#
# One track, eight bars, playing under everything for as long as the game is
# open. It has to come round without a seam and it has to stay welcome after
# the fortieth pass, which are different problems: the first is arithmetic and
# the second is restraint. So there is no melody doing anything clever, and
# nothing in it arrives more often than the ear stops noticing.

MUSIC_RATE = RATE    # 22050; the engine takes no other rate, see music()
BPM = 100
BEAT = MUSIC_RATE * 60 // BPM       # 13230 samples, exactly
BAR = BEAT * 4
BARS = 8

# Note names to frequencies, equal temperament from A4 = 440.
NOTE = {}
for _i, _n in enumerate("c cs d ds e f fs g gs a as b".split()):
    for _oct in range(9):
        NOTE["%s%d" % (_n, _oct)] = 440.0 * 2.0 ** ((12 + _oct * 12 + _i - 69) / 12.0)


def lowpass(buf, fc, rate, poles=2):
    """A one-pole lowpass, run `poles` times. Every voice here goes through
    one: the genre is a filter sweep with a band behind it, and a raw saw is
    the sound of something that has not been recorded yet."""
    a = 1.0 - math.exp(-2 * math.pi * fc / rate)
    for _ in range(poles):
        y = 0.0
        for i in range(len(buf)):
            y += a * (buf[i] - y)
            buf[i] = y
    return buf


def note_saw(f, dur, rate, decay=4.0, attack=0.004, cutoff=2200.0, detune=0.0):
    """A saw with an exponential decay. Two of them a few cents apart is the
    whole width of this mix, since it is mono and there is no chorus."""
    n = int(dur * rate)
    out = [0.0] * n
    voices = [f] if detune <= 0 else [f * (1 - detune), f * (1 + detune)]
    for vf in voices:
        ph = 0.0
        for i in range(n):
            ph = (ph + vf / rate) % 1.0
            out[i] += (2.0 * ph - 1.0) / len(voices)
    at = max(1, int(attack * rate))
    for i in range(n):
        x = i / n
        a = (i / at) if i < at else math.exp(-decay * x)
        out[i] *= a
    return lowpass(out, cutoff, rate)


def note_pad(f, dur, rate, cutoff=1400.0):
    """A pad: slow in, slow out, and detuned enough to beat gently. The rise
    and fall are the point -- an organ that arrives instantly is a stab."""
    n = int(dur * rate)
    out = [0.0] * n
    for vf in (f * 0.9965, f * 1.0035, f * 2.0):
        g = 0.35 if vf > f * 1.5 else 1.0
        ph = 0.0
        for i in range(n):
            ph = (ph + vf / rate) % 1.0
            out[i] += (2.0 * ph - 1.0) * g
    rise = int(0.35 * rate)
    fall = int(0.55 * rate)
    for i in range(n):
        a = 1.0
        if i < rise:
            a = i / rise
        if i > n - fall:
            a *= (n - i) / fall
        out[i] *= a
    return lowpass(out, cutoff, rate, poles=3)


def note_lead(f, dur, rate):
    """The one thing playing a tune. A sine with a fifth over it and a slow
    vibrato, quiet enough to be atmosphere rather than a part."""
    n = int(dur * rate)
    out = [0.0] * n
    ph = ph5 = 0.0
    for i in range(n):
        t = i / rate
        vib = 1.0 + 0.004 * math.sin(2 * math.pi * 5.2 * t)
        ph += 2 * math.pi * f * vib / rate
        ph5 += 2 * math.pi * f * 1.5 * vib / rate
        x = i / n
        a = min(1.0, i / (0.18 * rate)) * min(1.0, (n - i) / (0.4 * rate))
        out[i] = (math.sin(ph) + 0.3 * math.sin(ph5)) * a * (1.0 - 0.3 * x)
    return out


def kick(rate, rng):
    """Four to the bar. A sine dropping fast onto a floor, with a click on top
    so it survives being played over a firefight."""
    n = int(0.17 * rate)
    out = [0.0] * n
    ph = 0.0
    for i in range(n):
        x = i / n
        ph += 2 * math.pi * (135.0 * math.exp(-7.0 * x) + 44.0) / rate
        out[i] = math.sin(ph) * math.exp(-6.0 * x)
    click = int(0.005 * rate)
    for i in range(click):
        out[i] += rng.uniform(-1, 1) * 0.35 * (1.0 - i / click)
    return out


def snare(rate, rng, gate=0.19):
    """Two and four, with the gate that dates this music exactly. A tail is
    allowed to bloom and is then cut off flat rather than allowed to fade,
    which is a mistake somebody made in 1982 and everybody kept."""
    n = int(0.30 * rate)
    body = [rng.uniform(-1, 1) for _ in range(n)]
    body = lowpass(body, 5200.0, rate, poles=1)
    tone = 0.0
    ph = 0.0
    out = [0.0] * n
    for i in range(n):
        x = i / n
        ph += 2 * math.pi * 195.0 / rate
        tone = math.sin(ph) * math.exp(-16.0 * x) * 0.45
        # The tail decays slowly and then the gate shuts on it.
        env_body = math.exp(-22.0 * x)
        env_tail = math.exp(-3.2 * x) * 0.5
        g = 1.0
        cut = gate * rate
        if i > cut:
            g = max(0.0, 1.0 - (i - cut) / (0.012 * rate))
        out[i] = (body[i] * (env_body + env_tail) + tone) * g
    return out


def hat(rate, rng, dur=0.045):
    n = int(dur * rate)
    out = [rng.uniform(-1, 1) for _ in range(n)]
    lp = lowpass(list(out), 2500.0, rate, poles=1)
    for i in range(n):
        out[i] = (out[i] - lp[i]) * math.exp(-38.0 * (i / n))
    return out


class Track(Voice):
    """A fixed number of bars, mixed into by sample offset, wrapping.

    Wrapping is the whole trick. A pad still ringing when the buffer ends
    comes back at the start rather than being chopped, so the loop point has
    nothing in it to hear -- which is the difference between a loop and a
    repeat.
    """

    def at(self, pos, samples, gain=1.0):
        for i, v in enumerate(samples):
            self.buf[(pos + i) % self.n] += v * gain
        return self


def music():
    """The soundtrack: eight bars of synthwave that come round without a seam.

    Nothing here is sampled either. It is the genre's own furniture put up out
    of arithmetic -- eighth-note bass, a sixteenth arpeggio, a detuned pad,
    four on the floor under a gated snare -- over i-VI-III-VII in A minor,
    which is the progression the whole style is built on and the reason every
    track in it sounds like every other.

    Two things make it loop rather than restart. Everything is mixed in
    through `at`, which wraps. And a hundred beats a minute at sixteen
    kilohertz is 13230 samples a beat exactly, so eight bars is a whole number
    of samples and the seam lands on the downbeat rather than a hair off it.

    It is most of the download on its own -- one file against fourteen, and
    nineteen seconds against a fifth of a second -- and the obvious economy is
    to render it at a lower rate, since there is nothing in it above eight
    kilohertz except the hats. That does not work: the engine plays 22050 and
    44100 and nothing else, and a file at any other rate is built without
    complaint, shipped, and silent. Measured, not read: the whole track was
    inaudible at sixteen kilohertz with no error anywhere to say why.
    """
    rate = MUSIC_RATE
    n = BAR * BARS
    bed = Track(n / rate, rate)      # bass, arp, pad, lead -- ducked
    drums = Track(n / rate, rate)    # kick, snare, hats -- not
    rng = random.Random(20250802)

    # i - VI - III - VII, two bars each: the root, the arpeggio cell it is
    # played through, the pad voicing, and the note the lead holds over it.
    CHORDS = [
        ("a2",  ["a4", "c5", "e5", "c5"], ["a3", "c4", "e4"], "e5"),
        ("f2",  ["f4", "a4", "c5", "a4"], ["f3", "a3", "c4"], "c5"),
        ("c3",  ["e4", "g4", "c5", "g4"], ["e3", "g3", "c4"], "g4"),
        ("g2",  ["d4", "g4", "b4", "g4"], ["d3", "g3", "b3"], "d5"),
    ]

    for c, (root, cell, voicing, top) in enumerate(CHORDS):
        base = c * 2 * BAR

        # Pad: one chord held across its two bars, arriving before the bar it
        # belongs to so the change is a swell rather than an edit.
        for f in voicing:
            bed.at(base - int(0.12 * rate),
                   note_pad(NOTE[f], 2 * BAR / rate + 0.5, rate), 0.16)

        # Lead: one note, most of the two bars, and then out of the way.
        bed.at(base + BEAT, note_lead(NOTE[top], 2 * BAR / rate - BEAT / rate, rate), 0.10)

        for bar in range(2):
            b0 = base + bar * BAR

            # Bass on the eighths, up an octave for the last one, which is
            # what stops a driving bassline from being a drone.
            for e in range(8):
                f = NOTE[root] * (2.0 if e == 7 else 1.0)
                bed.at(b0 + e * BEAT // 2,
                       note_saw(f, 0.30, rate, decay=5.0, cutoff=900.0), 0.50)
                bed.at(b0 + e * BEAT // 2,
                       note_saw(f / 2, 0.26, rate, decay=6.0, cutoff=420.0), 0.22)

            # Arpeggio on the sixteenths, the cell four times a bar.
            for s in range(16):
                f = NOTE[cell[s % 4]] * (2.0 if bar == 1 and s >= 12 else 1.0)
                bed.at(b0 + s * BEAT // 4,
                       note_saw(f, 0.20, rate, decay=9.0, cutoff=3000.0,
                                detune=0.006),
                       0.16 if s % 2 else 0.22)

            # Four on the floor, snare on two and four, hats on the eighths
            # with the weight on the off-beat.
            for beat in range(4):
                drums.at(b0 + beat * BEAT, kick(rate, rng), 0.80)
                if beat % 2 == 1:
                    drums.at(b0 + beat * BEAT, snare(rate, rng), 0.34)
                drums.at(b0 + beat * BEAT, hat(rate, rng), 0.09)
                drums.at(b0 + beat * BEAT + BEAT // 2, hat(rate, rng), 0.16)

    # The turnaround: one extra snare on the last off-beat, so the eighth bar
    # points at the first instead of merely stopping next to it.
    drums.at(n - BEAT // 2, snare(rate, rng), 0.30)

    # Sidechain. Everything but the drums ducks under each kick and comes back
    # over the beat, which is the breathing this music is mostly made of.
    for i in range(n):
        x = (i % BEAT) / BEAT
        bed.buf[i] *= 0.55 + 0.45 * min(1.0, x / 0.45) ** 0.6

    for i in range(n):
        bed.buf[i] += drums.buf[i]
    return bed.drive(1.15)


def ui_move():
    v = Voice(0.035)
    v.square(1200, 900, 0.4, duty=0.4)
    v.noise(0.14, 6000, 2000, rng=random.Random(97))
    return v.highpass(400)


def ui_go():
    v = Voice(0.16)
    v.sine(520, 1040, 0.42, curve=1.4)
    v.square(260, 520, 0.16, duty=0.3, curve=1.4)
    return v.drive(1.4)


KIT = {
    "gun": gun, "bomb": bomb, "blast": blast, "death": death, "hit": hit,
    "bounce": bounce, "spawn": spawn, "prize": prize, "rust": rust,
    "charge": charge, "flag": flag,
    "thrust": thrust, "ui_move": ui_move, "ui_go": ui_go,
    "music": music,
}

SOUND_COMPONENT = """sound: "/sounds/%s.wav"
looping: %d
group: "%s"
gain: %.2f
pan: 0.0
speed: 1.0
loopcount: 0
"""

# The soundtrack is its own mixer group, because wanting the game loud and the
# music off is the commonest thing anybody wants from a game's audio and one
# gain cannot express it.
GROUP = {"music": "music"}

# Per-sound trim, so the mix is balanced at the source and the game never has
# to remember that bombs are loud. Thrust is held down for minutes at a time
# and everything else has to be audible over it, so it sits well under them.
GAIN = {
    "gun": 0.30, "bomb": 0.55, "blast": 0.80, "death": 0.85, "hit": 0.40,
    "bounce": 0.30, "spawn": 0.45, "prize": 0.45, "rust": 0.50,
    "charge": 0.55, "flag": 0.55,
    "thrust": 0.13, "ui_move": 0.35, "ui_go": 0.55,
    "music": 0.70,
}

# The ones that play until they are stopped. `loopcount: 0` with looping on is
# Defold's "forever".
LOOPING = {"thrust", "music"}


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "client/sounds"
    os.makedirs(out, exist_ok=True)
    only = sys.argv[2:]
    for name, make in sorted(KIT.items()):
        if only and name not in only:
            continue
        loop = name in LOOPING
        make().write(os.path.join(out, name + ".wav"), loop=loop)
        with open(os.path.join(out, name + ".sound"), "w") as f:
            f.write(SOUND_COMPONENT % (name, 1 if loop else 0,
                                       GROUP.get(name, "master"), GAIN[name]))


if __name__ == "__main__":
    main()
