// Write the sound kit out as wav files, for listening to.
//
// The game generates its own audio at boot and ships none, so there is no
// longer a file anywhere to open in a player when a sound needs tuning. This
// is that file, on demand, from the same C the client runs. It is a debugging
// tool and a listening tool, never a build step: nothing in client/sounds/ is
// generated by it, and nothing it writes is checked in.
//
//     make -C client/tools sfx && client/tools/sfxdump /tmp/kit
//
// Naming sounds after the argument writes only those, which is what you want
// when you are on the fortieth pass at the bomb and the soundtrack takes most
// of the time.
//
//     client/tools/sfxdump /tmp/kit bomb blast

#include "../ext/simcore/src/sfx.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int wanted(const char *name, int argc, char **argv) {
    int i;
    if (argc <= 2) return 1;
    for (i = 2; i < argc; i++)
        if (strcmp(name, argv[i]) == 0) return 1;
    return 0;
}

int main(int argc, char **argv) {
    const char *dir = argc > 1 ? argv[1] : "/tmp/kit";
    int i;

    for (i = 0; sfx_names[i]; i++) {
        char path[512];
        unsigned char *wav;
        size_t len = 0;
        FILE *f;

        if (!wanted(sfx_names[i], argc, argv)) continue;

        wav = sfx_render(sfx_names[i], &len);
        if (!wav) {
            fprintf(stderr, "sfxdump: cannot render '%s'\n", sfx_names[i]);
            return 1;
        }
        snprintf(path, sizeof(path), "%s/%s.wav", dir, sfx_names[i]);
        f = fopen(path, "wb");
        if (!f) {
            perror(path);
            free(wav);
            return 1;
        }
        if (fwrite(wav, 1, len, f) != len) {
            perror(path);
            fclose(f);
            free(wav);
            return 1;
        }
        fclose(f);
        free(wav);
        printf("%-12s %5.0f ms  %6ld bytes\n", sfx_names[i],
               (len - 44) / 2.0 / 22050.0 * 1000.0, (long)(len - 44));
    }
    return 0;
}
