-- Sound.
--
-- Every effect is generated by client/tools/mksounds.py and lives in
-- client/sounds/. Nothing here was recorded, sampled or sourced, which is the
-- rule in docs/design/identity.md and the reason the generator is checked in
-- next to its output.
--
-- The job of this module is restraint. A nine-ship arena fires several
-- hundred bolts a minute, and a client that played all of them at full gain
-- would be unlistenable inside ten seconds. So: distance attenuation, stereo
-- placement, a small pitch spread so repeats do not phase into a machine gun,
-- and a hard per-frame budget per sound.

local M = {}

local RANGE = 760          -- world pixels beyond which a sound is inaudible
local lx, ly = 0, 0

-- How many of each may start in a single frame. A firefight is meant to sound
-- busy, not additive.
local BUDGET = {
    gun = 3, hit = 3, bounce = 2, blast = 2, death = 2, bomb = 2,
}
local DEFAULT_BUDGET = 1

local spent = {}
local seed = 991
local function rnd()
    seed = (seed * 1103515245 + 12345) % 2147483648
    return seed / 2147483648
end

function M.listener(x, y)
    lx, ly = x, y
end

-- Called once per frame, before events are drained.
function M.frame()
    for k in pairs(spent) do spent[k] = nil end
end

-- A world sound. Quiet things far away are dropped outright rather than
-- played at a gain nobody can hear, which is what keeps the voice count down
-- in a busy arena.
function M.play(name, x, y)
    local n = (spent[name] or 0) + 1
    if n > (BUDGET[name] or DEFAULT_BUDGET) then return end
    spent[name] = n

    local gain, pan = 1, 0
    if x then
        local dx, dy = x - lx, y - ly
        local d = math.sqrt(dx * dx + dy * dy)
        if d >= RANGE then return end
        local k = 1 - d / RANGE
        gain = k * k
        if gain < 0.035 then return end
        pan = dx / (RANGE * 0.55)
        if pan > 1 then pan = 1 elseif pan < -1 then pan = -1 end
    end

    M.fire(name, {
        gain = gain,
        pan = pan,
        speed = 0.93 + rnd() * 0.14,
    })
end

-- Interface sounds are not in the world and are never attenuated.
function M.ui(name)
    M.fire(name, {gain = 1, pan = 0, speed = 1})
end

-- One place where a sound actually starts.
--
-- Guarded, because a sound component that failed to load must not take the
-- frame loop with it -- but reported, once, because a client that has gone
-- silent looks exactly like a client with the volume down and nothing in the
-- log would ever say which. Swallowing this is how audio stays broken.
local complained = false
function M.fire(name, opts)
    local ok, err = pcall(sound.play, "#" .. name, opts)
    if ok or complained then return end
    complained = true
    print("SOUND: cannot play '" .. name .. "': " .. tostring(err))
end

return M
