/* Generates src/sintab.h: a 4096-entry quarter-scaled sine table in Q15.
 *
 * The sim core uses no floating point at runtime. This generator is the one
 * place trigonometry happens, at build-authoring time, and its output is
 * committed so every platform compiles the identical table.
 *
 *   cc -O2 -o gen_sintab tools/gen_sintab.c -lm && ./gen_sintab > src/sintab.h
 */
#include <math.h>
#include <stdio.h>

#define N 4096

int main(void) {
    const double pi = acos(-1.0);
    printf("/* Generated by tools/gen_sintab.c. Do not edit. */\n");
    printf("static const int16_t sim_sintab[%d] = {\n", N);
    for (int i = 0; i < N; i++) {
        double v = sin(2.0 * pi * (double)i / (double)N) * 32767.0;
        long r = lround(v);
        printf("%6ld,%s", r, (i % 8 == 7) ? "\n" : " ");
    }
    printf("};\n");
    return 0;
}
