#!/usr/bin/env python3
"""Lift the seven hull drawings out of the client and write them as C.

`client/arena/world.lua` is where a hull's shape actually lives: an outline in
local pixels, the plates and panel lines inside it, the canopy, the hardpoints,
the lamps and the engine mouths, plus a `fit` that squeezes all of it into the
collision footprint `sim/src/baseline.c` gives that class. This reads that
table, applies the fit exactly as the client does at load, and writes
`hulls_data.h`.

Reading it rather than retyping it is the whole point: a 3D hull that is not
the 2D hull is a picture of a ship this game does not have.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
LUA = os.path.join(ROOT, "client", "arena", "world.lua")

NAMES = ["Apex", "Wedge", "Chord", "Anvil", "Cipher", "Facet", "Lattice"]


class Reader:
    """Just enough Lua to read a table of numbers, names and nested tables."""

    def __init__(self, text):
        self.s = text
        self.i = 0

    def skip(self):
        while self.i < len(self.s):
            c = self.s[self.i]
            if c in " \t\r\n,;":
                self.i += 1
            elif self.s.startswith("--", self.i):
                nl = self.s.find("\n", self.i)
                self.i = len(self.s) if nl < 0 else nl + 1
            else:
                return

    def value(self):
        self.skip()
        if self.s[self.i] == "{":
            return self.table()
        m = re.match(r"-?\d+(\.\d+)?([eE][-+]?\d+)?", self.s[self.i:])
        if m:
            self.i += m.end()
            return float(m.group(0))
        m = re.match(r"true|false|nil", self.s[self.i:])
        if m:
            self.i += m.end()
            return {"true": True, "false": False, "nil": None}[m.group(0)]
        raise SyntaxError("value at %r" % self.s[self.i:self.i + 40])

    def table(self):
        assert self.s[self.i] == "{"
        self.i += 1
        out, arr = {}, []
        while True:
            self.skip()
            if self.s[self.i] == "}":
                self.i += 1
                return out if out else arr
            m = re.match(r"([A-Za-z_]\w*)\s*=", self.s[self.i:])
            if m:
                self.i += m.end()
                out[m.group(1)] = self.value()
            else:
                arr.append(self.value())


def hulls():
    text = open(LUA, encoding="utf-8").read()
    start = text.index("M.HULLS = {")
    return Reader(text[start + len("M.HULLS = "):]).value()


def refit(h):
    """The client's own refit, so the mesh sits in the collision footprint."""
    f = h.pop("fit")
    sx, sy, oy = f[0], f[1], f[2]
    line = (sx * sy) ** 0.5

    def pts(t):
        for i in range(0, len(t), 2):
            t[i] *= sx
            t[i + 1] = t[i + 1] * sy + oy

    for key in ("poly", "canopy", "jets"):
        if key in h:
            pts(h[key])
    for key in ("plates", "lines"):
        for q in h.get(key, []):
            pts(q)
    for q in h.get("pods", []):
        q[0], q[1], q[2] = q[0] * sx, q[1] * sy + oy, q[2] * line
    for q in h.get("tubes", []):
        q[0], q[1] = q[0] * sx, q[1] * sy + oy
        q[2], q[3] = q[2] * sx, q[3] * sy + oy
        q[4] = q[4] * line


def flat(name, rows, width):
    """A flat float array plus the row starts, since C has no ragged lists."""
    body, starts = [], []
    for r in rows:
        starts.append(len(body) // width if width else len(body))
        body.extend(r)
    return name, body, starts


def emit(hs, out):
    w = out.write
    w("/* Generated by hull_export.py. Do not edit: edit the hulls in\n"
      " * client/arena/world.lua and run `make hulls`. */\n"
      "#ifndef HULLS_DATA_H\n#define HULLS_DATA_H\n\n"
      "#define HULL_COUNT %d\n\n" % len(hs))
    w("static const char *const HULL_NAME[HULL_COUNT] = {%s};\n\n"
      % ", ".join('"%s"' % n for n in NAMES))

    def arr(kind, name, vals, fmt="%.5ff"):
        w("static const %s %s[] = {%s};\n"
          % (kind, name, ", ".join(fmt % v for v in vals) if vals else "0"))

    for i, h in enumerate(hs):
        arr("float", "hull%d_poly" % i, h["poly"])
        arr("float", "hull%d_canopy" % i, h.get("canopy", []))
        arr("float", "hull%d_jets" % i, h.get("jets", []))
        plates = h.get("plates", [])
        arr("float", "hull%d_plate_pts" % i, [v for q in plates for v in q])
        arr("int", "hull%d_plate_len" % i, [len(q) for q in plates], "%d")
        lines = h.get("lines", [])
        arr("float", "hull%d_line_pts" % i, [v for q in lines for v in q])
        arr("int", "hull%d_line_len" % i, [len(q) for q in lines], "%d")
        arr("float", "hull%d_tubes" % i, [v for q in h.get("tubes", []) for v in q])
        arr("float", "hull%d_pods" % i, [v for q in h.get("pods", []) for v in q])
        w("\n")

    w("typedef struct {\n"
      "    const char *name;\n"
      "    const float *poly; int poly_n;      /* the silhouette, xy pairs */\n"
      "    const float *canopy; int canopy_n;\n"
      "    const float *jets; int jets_n;      /* engine mouths, xy pairs */\n"
      "    const float *plate_pts; const int *plate_len; int plate_n;\n"
      "    const float *line_pts; const int *line_len; int line_n;\n"
      "    const float *tubes; int tube_n;     /* x0 y0 x1 y1 radius */\n"
      "    const float *pods; int pod_n;       /* x y radius */\n"
      "    float dim;\n"
      "} hull_art;\n\n")
    w("static const hull_art HULLS[HULL_COUNT] = {\n")
    for i, h in enumerate(hs):
        w("    {HULL_NAME[%d],\n" % i)
        w("     hull%d_poly, %d, hull%d_canopy, %d, hull%d_jets, %d,\n"
          % (i, len(h["poly"]) // 2, i, len(h.get("canopy", [])) // 2,
             i, len(h.get("jets", [])) // 2))
        w("     hull%d_plate_pts, hull%d_plate_len, %d,\n"
          % (i, i, len(h.get("plates", []))))
        w("     hull%d_line_pts, hull%d_line_len, %d,\n"
          % (i, i, len(h.get("lines", []))))
        w("     hull%d_tubes, %d, hull%d_pods, %d, %.4ff},\n"
          % (i, len(h.get("tubes", [])), i, len(h.get("pods", [])),
             h.get("dim", 1.0)))
    w("};\n\n#endif\n")


def main():
    hs = hulls()
    if len(hs) != len(NAMES):
        sys.exit("world.lua has %d hulls, expected %d" % (len(hs), len(NAMES)))
    for h in hs:
        refit(h)
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "hulls_data.h")
    with open(path, "w", encoding="utf-8") as out:
        emit(hs, out)
    for name, h in zip(NAMES, hs):
        ys = h["poly"][1::2]
        xs = h["poly"][0::2]
        print("%-8s %2d verts  nose %6.2f  tail %6.2f  beam %6.2f"
              % (name, len(xs), max(ys), -min(ys), max(xs) - min(xs)))


if __name__ == "__main__":
    main()
