/* Generated by hull_export.py. Do not edit: edit the hulls in
 * client/arena/world.lua and run `make hulls`. */
#ifndef HULLS_DATA_H
#define HULLS_DATA_H

#define HULL_COUNT 7

static const char *const HULL_NAME[HULL_COUNT] = {"Apex", "Wedge", "Chord", "Anvil", "Cipher", "Facet", "Lattice"};

static const float hull0_poly[] = {0.00000f, 20.49621f, 1.60000f, 11.42803f, 2.60000f, 4.37500f, 6.50000f, -1.67045f, 11.00000f, -9.73106f, 8.50000f, -12.25000f, 3.50000f, -7.21212f, 3.00000f, -11.24242f, 0.00000f, -12.25000f, -3.00000f, -11.24242f, -3.50000f, -7.21212f, -8.50000f, -12.25000f, -11.00000f, -9.73106f, -6.50000f, -1.67045f, -2.60000f, 4.37500f, -1.60000f, 11.42803f};
static const float hull0_canopy[] = {0.00000f, 14.95455f, 1.50000f, 9.91667f, 0.00000f, 6.99470f, -1.50000f, 9.91667f};
static const float hull0_jets[] = {-1.80000f, -11.74621f, 1.80000f, -11.74621f};
static const float hull0_plate_pts[] = {0.00000f, 5.88636f, 2.20000f, 1.35227f, 1.80000f, -6.70833f, 0.00000f, -8.72348f, -1.80000f, -6.70833f, -2.20000f, 1.35227f};
static const int hull0_plate_len[] = {12};
static const float hull0_line_pts[] = {0.00000f, 19.28712f, 2.60000f, 4.37500f, 6.50000f, -1.67045f, 0.00000f, 19.28712f, -2.60000f, 4.37500f, -6.50000f, -1.67045f, 5.00000f, -0.46136f, 9.30000f, -8.92500f, -5.00000f, -0.46136f, -9.30000f, -8.92500f, 2.60000f, 0.84848f, 6.00000f, -2.27500f, -2.60000f, 0.84848f, -6.00000f, -2.27500f};
static const int hull0_line_len[] = {6, 6, 4, 4, 4, 4};
static const float hull0_tubes[] = {4.20000f, 2.35985f, 4.20000f, -1.67045f, 1.40529f, -4.20000f, 2.35985f, -4.20000f, -1.67045f, 1.40529f};
static const float hull0_pods[] = {0.00000f, 19.48864f, 1.50567f};

static const float hull1_poly[] = {0.00000f, 12.00000f, 2.70156f, 11.16981f, 4.77969f, 6.60377f, 7.48125f, 1.62264f, 16.10547f, -4.18868f, 16.62500f, -7.09434f, 9.35156f, -5.84906f, 8.31250f, -8.75472f, 3.32500f, -10.00000f, 0.00000f, -10.00000f, -3.32500f, -10.00000f, -8.31250f, -8.75472f, -9.35156f, -5.84906f, -16.62500f, -7.09434f, -16.10547f, -4.18868f, -7.48125f, 1.62264f, -4.77969f, 6.60377f, -2.70156f, 11.16981f};
static const float hull1_canopy[] = {0.00000f, 10.67170f, 1.87031f, 8.84528f, 1.66250f, 6.68679f, -1.66250f, 6.68679f, -1.87031f, 8.84528f};
static const float hull1_jets[] = {-5.81875f, -9.58491f, 5.81875f, -9.58491f};
static const float hull1_plate_pts[] = {3.53281f, 4.52830f, 3.53281f, -7.92453f, -3.53281f, -7.92453f, -3.53281f, 4.52830f};
static const int hull1_plate_len[] = {8};
static const float hull1_line_pts[] = {7.48125f, 1.62264f, 15.58594f, -3.93962f, -7.48125f, 1.62264f, -15.58594f, -3.93962f, 11.42969f, -1.44906f, 12.05312f, -5.60000f, -11.42969f, -1.44906f, -12.05312f, -5.60000f, 4.57188f, 4.03019f, 4.57188f, -6.26415f, -4.57188f, 4.03019f, -4.57188f, -6.26415f, -3.53281f, -1.69811f, 3.53281f, -1.69811f};
static const int hull1_line_len[] = {4, 4, 4, 4, 4, 4, 4};
static const float hull1_tubes[] = {0.00000f, 3.36604f, 0.00000f, -6.76226f, 2.97207f};
static const float hull1_pods[] = {0};

static const float hull2_poly[] = {0.00000f, 10.00000f, 6.27344f, 8.61538f, 13.11719f, 4.46154f, 18.82031f, -2.00000f, 20.53125f, -6.15385f, 16.53906f, -8.00000f, 12.54688f, -4.76923f, 7.41406f, -1.07692f, 2.85156f, 0.76923f, 0.00000f, 1.04615f, -2.85156f, 0.76923f, -7.41406f, -1.07692f, -12.54688f, -4.76923f, -16.53906f, -8.00000f, -20.53125f, -6.15385f, -18.82031f, -2.00000f, -13.11719f, 4.46154f, -6.27344f, 8.61538f};
static const float hull2_canopy[] = {0.00000f, 6.95385f, 1.48281f, 5.29231f, 0.00000f, 3.44615f, -1.48281f, 5.29231f};
static const float hull2_jets[] = {-9.69531f, -4.49231f, 9.69531f, -4.49231f};
static const float hull2_plate_pts[] = {0.00000f, 8.15385f, 2.50938f, 6.30769f, 2.50938f, 3.53846f, 0.00000f, 2.15385f, -2.50938f, 3.53846f, -2.50938f, 6.30769f, 14.60000f, -3.01538f, 18.70625f, -5.60000f, 17.10938f, -7.63077f, 13.23125f, -4.67692f, -13.23125f, -4.67692f, -17.10938f, -7.63077f, -18.70625f, -5.60000f, -14.60000f, -3.01538f};
static const int hull2_plate_len[] = {12, 8, 8};
static const float hull2_line_pts[] = {4.56250f, 7.32308f, 15.05625f, 0.49231f, -4.56250f, 7.32308f, -15.05625f, 0.49231f, 2.85156f, 0.76923f, 6.27344f, 8.24615f, -2.85156f, 0.76923f, -6.27344f, 8.24615f, 9.12500f, -2.09231f, 10.95000f, 2.70769f, -9.12500f, -2.09231f, -10.95000f, 2.70769f};
static const int hull2_line_len[] = {4, 4, 4, 4, 4, 4};
static const float hull2_tubes[] = {17.10938f, -4.30769f, 17.10938f, -0.06154f, 1.43654f, -17.10938f, -4.30769f, -17.10938f, -0.06154f, 1.43654f};
static const float hull2_pods[] = {0.00000f, 5.20000f, 2.46264f};

static const float hull3_poly[] = {0.00000f, 12.75972f, 6.50000f, 11.99647f, 11.00000f, 7.98940f, 13.50000f, 1.31095f, 13.50000f, -5.36749f, 11.00000f, -10.61484f, 6.50000f, -13.00000f, 0.00000f, -13.00000f, -6.50000f, -13.00000f, -11.00000f, -10.61484f, -13.50000f, -5.36749f, -13.50000f, 1.31095f, -11.00000f, 7.98940f, -6.50000f, 11.99647f};
static const float hull3_canopy[] = {3.40000f, 11.80565f, 2.60000f, 9.32509f, -2.60000f, 9.32509f, -3.40000f, 11.80565f};
static const float hull3_jets[] = {-9.00000f, -11.66431f, -3.50000f, -13.00000f, 3.50000f, -13.00000f, 9.00000f, -11.66431f};
static const float hull3_plate_pts[] = {9.00000f, 10.27915f, 11.40000f, 6.46290f, -11.40000f, 6.46290f, -9.00000f, 10.27915f, 0.00000f, 3.60071f, 4.20000f, -1.55124f, 0.00000f, -6.70318f, -4.20000f, -1.55124f};
static const int hull3_plate_len[] = {8, 8};
static const float hull3_line_pts[] = {9.00000f, 6.08127f, 9.00000f, -9.18375f, -9.00000f, 6.08127f, -9.00000f, -9.18375f, 5.60000f, 1.50177f, 9.00000f, 1.50177f, -5.60000f, 1.50177f, -9.00000f, 1.50177f, 5.60000f, -4.60424f, 9.00000f, -4.60424f, -5.60000f, -4.60424f, -9.00000f, -4.60424f, -8.00000f, -10.71025f, 8.00000f, -10.71025f};
static const int hull3_line_len[] = {4, 4, 4, 4, 4, 4, 4};
static const float hull3_tubes[] = {5.20000f, 7.60777f, 5.20000f, 12.95053f, 2.14888f, -5.20000f, 7.60777f, -5.20000f, 12.95053f, 2.14888f};
static const float hull3_pods[] = {0};

static const float hull4_poly[] = {0.00000f, 22.00000f, 2.35385f, 3.75000f, 4.70769f, -6.51562f, 4.15385f, -14.50000f, 9.00000f, -18.49219f, 3.04615f, -17.35156f, 2.21538f, -19.06250f, 0.00000f, -19.06250f, -2.21538f, -19.06250f, -3.04615f, -17.35156f, -9.00000f, -18.49219f, -4.15385f, -14.50000f, -4.70769f, -6.51562f, -2.35385f, 3.75000f};
static const float hull4_canopy[] = {0.00000f, 15.72656f, 1.24615f, 11.73438f, 0.00000f, 8.88281f, -1.24615f, 11.73438f};
static const float hull4_jets[] = {0.00000f, -19.06250f};
static const float hull4_plate_pts[] = {0.00000f, 17.43750f, 1.93846f, 0.32812f, 0.00000f, -11.07812f, -1.93846f, 0.32812f};
static const int hull4_plate_len[] = {8};
static const float hull4_line_pts[] = {0.00000f, 21.31562f, 4.43077f, -6.51562f, 0.00000f, 21.31562f, -4.43077f, -6.51562f, 4.43077f, -14.95625f, 8.16923f, -18.15000f, -4.43077f, -14.95625f, -8.16923f, -18.15000f};
static const int hull4_line_len[] = {4, 4, 4, 4};
static const float hull4_tubes[] = {0};
static const float hull4_pods[] = {0};

static const float hull5_poly[] = {0.00000f, 14.00000f, 4.93043f, 9.66071f, 9.97826f, 5.32143f, 13.50000f, -2.39286f, 11.15217f, -10.10714f, 5.28261f, -13.00000f, 0.00000f, -13.00000f, -5.28261f, -13.00000f, -11.15217f, -10.10714f, -13.50000f, -2.39286f, -9.97826f, 5.32143f, -4.93043f, 9.66071f};
static const float hull5_canopy[] = {0.00000f, 8.79286f, 2.81739f, 5.70714f, 0.00000f, 3.77857f, -2.81739f, 5.70714f};
static const float hull5_jets[] = {-3.05217f, -13.00000f, 3.05217f, -13.00000f};
static const float hull5_plate_pts[] = {0.00000f, 10.62500f, 5.40000f, 5.70714f, 4.69565f, -1.42857f, -4.69565f, -1.42857f, -5.40000f, 5.70714f, 5.16522f, -4.70714f, 4.22609f, -10.49286f, -4.22609f, -10.49286f, -5.16522f, -4.70714f};
static const int hull5_plate_len[] = {10, 8};
static const float hull5_line_pts[] = {0.00000f, 13.42143f, 9.39130f, 5.70714f, 0.00000f, 13.42143f, -9.39130f, 5.70714f, 12.44348f, -2.00714f, 10.33043f, -9.33571f, -12.44348f, -2.00714f, -10.33043f, -9.33571f, 5.40000f, 1.46429f, 12.79565f, -0.07857f, -5.40000f, 1.46429f, -12.79565f, -0.07857f, 7.27826f, -4.32143f, 7.27826f, -10.10714f, -7.27826f, -4.32143f, -7.27826f, -10.10714f};
static const int hull5_line_len[] = {4, 4, 4, 4, 4, 4, 4, 4};
static const float hull5_tubes[] = {7.74783f, 6.47857f, 7.74783f, 12.65000f, 2.34069f, -7.74783f, 6.47857f, -7.74783f, 12.65000f, 2.34069f};
static const float hull5_pods[] = {0};

static const float hull6_poly[] = {0.00000f, 14.00000f, 2.47576f, 10.17068f, 2.47576f, 4.21396f, 10.16830f, 3.36300f, 13.26300f, 0.81012f, 10.16830f, -1.74276f, 2.47576f, -2.59372f, 2.47576f, -9.82688f, 1.76840f, -12.37976f, 0.00000f, -12.37976f, -1.76840f, -12.37976f, -2.47576f, -9.82688f, -2.47576f, -2.59372f, -10.16830f, -1.74276f, -13.26300f, 0.81012f, -10.16830f, 3.36300f, -2.47576f, 4.21396f, -2.47576f, 10.17068f};
static const float hull6_canopy[] = {0.00000f, 11.95770f, 1.32630f, 10.25578f, 0.00000f, 8.72405f, -1.32630f, 10.25578f};
static const float hull6_jets[] = {-1.59156f, -12.37976f, 1.59156f, -12.37976f};
static const float hull6_plate_pts[] = {0.00000f, 3.78848f, 2.82944f, 0.81012f, 0.00000f, -2.16824f, -2.82944f, 0.81012f};
static const int hull6_plate_len[] = {8};
static const float hull6_line_pts[] = {3.97890f, 3.10771f, 5.30520f, -2.33843f, -3.97890f, 3.10771f, -5.30520f, -2.33843f, 6.63150f, 2.85242f, 7.95780f, -2.16824f, -6.63150f, 2.85242f, -7.95780f, -2.16824f, -2.47576f, 9.74520f, 2.47576f, 7.70290f, 2.47576f, 7.19232f, -2.47576f, 5.15002f, -2.47576f, -4.38074f, 2.47576f, -6.42304f, 2.47576f, -6.93362f, -2.47576f, -8.97592f};
static const int hull6_line_len[] = {4, 4, 4, 4, 4, 4, 4, 4};
static const float hull6_tubes[] = {0};
static const float hull6_pods[] = {12.02512f, 0.81012f, 1.47462f, -12.02512f, 0.81012f, 1.47462f, 0.00000f, -11.69899f, 1.30113f};

typedef struct {
    const char *name;
    const float *poly; int poly_n;      /* the silhouette, xy pairs */
    const float *canopy; int canopy_n;
    const float *jets; int jets_n;      /* engine mouths, xy pairs */
    const float *plate_pts; const int *plate_len; int plate_n;
    const float *line_pts; const int *line_len; int line_n;
    const float *tubes; int tube_n;     /* x0 y0 x1 y1 radius */
    const float *pods; int pod_n;       /* x y radius */
    float dim;
} hull_art;

static const hull_art HULLS[HULL_COUNT] = {
    {HULL_NAME[0],
     hull0_poly, 16, hull0_canopy, 4, hull0_jets, 2,
     hull0_plate_pts, hull0_plate_len, 1,
     hull0_line_pts, hull0_line_len, 6,
     hull0_tubes, 2, hull0_pods, 1, 1.0000f},
    {HULL_NAME[1],
     hull1_poly, 18, hull1_canopy, 5, hull1_jets, 2,
     hull1_plate_pts, hull1_plate_len, 1,
     hull1_line_pts, hull1_line_len, 7,
     hull1_tubes, 1, hull1_pods, 0, 1.0000f},
    {HULL_NAME[2],
     hull2_poly, 18, hull2_canopy, 4, hull2_jets, 2,
     hull2_plate_pts, hull2_plate_len, 3,
     hull2_line_pts, hull2_line_len, 6,
     hull2_tubes, 2, hull2_pods, 1, 1.0000f},
    {HULL_NAME[3],
     hull3_poly, 14, hull3_canopy, 4, hull3_jets, 4,
     hull3_plate_pts, hull3_plate_len, 2,
     hull3_line_pts, hull3_line_len, 7,
     hull3_tubes, 2, hull3_pods, 0, 1.0000f},
    {HULL_NAME[4],
     hull4_poly, 14, hull4_canopy, 4, hull4_jets, 1,
     hull4_plate_pts, hull4_plate_len, 1,
     hull4_line_pts, hull4_line_len, 4,
     hull4_tubes, 0, hull4_pods, 0, 0.7200f},
    {HULL_NAME[5],
     hull5_poly, 12, hull5_canopy, 4, hull5_jets, 2,
     hull5_plate_pts, hull5_plate_len, 2,
     hull5_line_pts, hull5_line_len, 8,
     hull5_tubes, 2, hull5_pods, 0, 1.0000f},
    {HULL_NAME[6],
     hull6_poly, 18, hull6_canopy, 4, hull6_jets, 2,
     hull6_plate_pts, hull6_plate_len, 1,
     hull6_line_pts, hull6_line_len, 8,
     hull6_tubes, 0, hull6_pods, 3, 1.0000f},
};

#endif
